version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: US/Arizona
  open-pull-requests-limit: 3
  assignees:
  - peterdemartini
  ignore:
  - dependency-name: "@types/node"
    versions:
    - "> 14.14.37"
  - dependency-name: ts-transforms
    versions:
    - 0.50.0
    - 0.56.1
  - dependency-name: "@terascope/utils"
    versions:
    - 0.35.0
    - 0.36.2
    - 0.36.3
    - 0.36.4
    - 0.36.7
    - 0.37.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
  - dependency-name: "@types/node"
    versions:
    - 14.14.25
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.34
    - 14.14.35
  - dependency-name: "@terascope/job-components"
    versions:
    - 0.45.0
