# set the dist to bionic
dist: bionic
language: node_js
node_js:
  - '10.16'
  - '12.13'
os:
  - linux
  - osx
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/
cache:
  npm: false
  yarn: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - yarn lint
  - yarn global add teraslice-cli
  - teraslice-cli assets build
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build/*.zip
  skip_cleanup: true
  on:
    tags: true
