# set the dist to bionic
dist: bionic
language: node_js
node_js:
  - '12.22'
  - '14.17'
os:
  - linux
  - osx
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+/
if: NOT (branch = master AND type = push AND tag IS blank AND os = osx)
cache:
  npm: false
  yarn: false
before_script:
  - yarn build
  - yarn global add teraslice-cli
script:
  - yarn test
  - yarn lint
  - teraslice-cli -v
  - teraslice-cli assets build
  - teraslice-cli assets build --bundle
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build/*.zip
  skip_cleanup: true
  on:
    tags: true
