// NOTE: This code is auto-generated by `teraslice-cli assets registry`
// any manual changes will be lost next time this gets auto-generated.

import Accumulate from '../src/accumulate/processor.js';
import AccumulateSchema from '../src/accumulate/schema.js';

import AccumulateByKey from '../src/accumulate_by_key/processor.js';
import AccumulateByKeySchema from '../src/accumulate_by_key/schema.js';

import AddKey from '../src/add_key/processor.js';
import AddKeySchema from '../src/add_key/schema.js';

import AddShortId from '../src/add_short_id/processor.js';
import AddShortIdSchema from '../src/add_short_id/schema.js';

import CopyField from '../src/copy_field/processor.js';
import CopyFieldSchema from '../src/copy_field/schema.js';

import CopyMetadataField from '../src/copy_metadata_field/processor.js';
import CopyMetadataFieldSchema from '../src/copy_metadata_field/schema.js';

import CountByField from '../src/count_by_field/processor.js';
import CountByFieldSchema from '../src/count_by_field/schema.js';

import CountUnique from '../src/count_unique/processor.js';
import CountUniqueSchema from '../src/count_unique/schema.js';

import CreateGeopoint from '../src/create_geopoint/processor.js';
import CreateGeopointSchema from '../src/create_geopoint/schema.js';

import DataGeneratorFetcher from '../src/data_generator/fetcher.js';
import DataGeneratorSchema from '../src/data_generator/schema.js';
import DataGeneratorSlicer from '../src/data_generator/slicer.js';

import DataWindowToArray from '../src/data_window_to_array/processor.js';
import DataWindowToArraySchema from '../src/data_window_to_array/schema.js';

import DateRouter from '../src/date_router/processor.js';
import DateRouterSchema from '../src/date_router/schema.js';

import DebugRoutes from '../src/debug_routes/processor.js';
import DebugRoutesSchema from '../src/debug_routes/schema.js';

import Dedupe from '../src/dedupe/processor.js';
import DedupeSchema from '../src/dedupe/schema.js';

import DropField from '../src/drop_field/processor.js';
import DropFieldSchema from '../src/drop_field/schema.js';

import DropFieldConditional from '../src/drop_field_conditional/processor.js';
import DropFieldConditionalSchema from '../src/drop_field_conditional/schema.js';

import Extraction from '../src/extraction/processor.js';
import ExtractionSchema from '../src/extraction/schema.js';

import FieldRouter from '../src/field_router/processor.js';
import FieldRouterSchema from '../src/field_router/schema.js';

import Filter from '../src/filter/processor.js';
import FilterSchema from '../src/filter/schema.js';

import FilterByDate from '../src/filter_by_date/processor.js';
import FilterByDateSchema from '../src/filter_by_date/schema.js';

import FilterByRequiredFields from '../src/filter_by_required_fields/processor.js';
import FilterByRequiredFieldsSchema from '../src/filter_by_required_fields/schema.js';

import FilterByUnknownFields from '../src/filter_by_unknown_fields/processor.js';
import FilterByUnknownFieldsSchema from '../src/filter_by_unknown_fields/schema.js';

import FlattenObject from '../src/flatten_object/processor.js';
import FlattenObjectSchema from '../src/flatten_object/schema.js';

import GroupBy from '../src/group_by/processor.js';
import GroupBySchema from '../src/group_by/schema.js';

import HashRouter from '../src/hash_router/processor.js';
import HashRouterSchema from '../src/hash_router/schema.js';

import JsonParser from '../src/json_parser/processor.js';
import JsonParserSchema from '../src/json_parser/schema.js';

import KeepField from '../src/keep_field/processor.js';
import KeepFieldSchema from '../src/keep_field/schema.js';

import KeyRouter from '../src/key_router/processor.js';
import KeyRouterSchema from '../src/key_router/schema.js';

import Match from '../src/match/processor.js';
import MatchSchema from '../src/match/schema.js';

import Output from '../src/output/processor.js';
import OutputSchema from '../src/output/schema.js';

import PostProcess from '../src/post_process/processor.js';
import PostProcessSchema from '../src/post_process/schema.js';

import RemoveEmptyFields from '../src/remove_empty_fields/processor.js';
import RemoveEmptyFieldsSchema from '../src/remove_empty_fields/schema.js';

import RemoveKey from '../src/remove_key/processor.js';
import RemoveKeySchema from '../src/remove_key/schema.js';

import RenameField from '../src/rename_field/processor.js';
import RenameFieldSchema from '../src/rename_field/schema.js';

import RoutedSender from '../src/routed_sender/processor.js';
import RoutedSenderSchema from '../src/routed_sender/schema.js';

import SampleExact from '../src/sample_exact/processor.js';
import SampleExactSchema from '../src/sample_exact/schema.js';

import SampleExactEsPercent from '../src/sample_exact_es_percent/processor.js';
import SampleExactEsPercentSchema from '../src/sample_exact_es_percent/schema.js';

import SampleRandom from '../src/sample_random/processor.js';
import SampleRandomSchema from '../src/sample_random/schema.js';

import Selection from '../src/selection/processor.js';
import SelectionSchema from '../src/selection/schema.js';

import SetField from '../src/set_field/processor.js';
import SetFieldSchema from '../src/set_field/schema.js';

import SetFieldConditional from '../src/set_field_conditional/processor.js';
import SetFieldConditionalSchema from '../src/set_field_conditional/schema.js';

import SetKey from '../src/set_key/processor.js';
import SetKeySchema from '../src/set_key/schema.js';

import Sort from '../src/sort/processor.js';
import SortSchema from '../src/sort/schema.js';

import Stdout from '../src/stdout/processor.js';
import StdoutSchema from '../src/stdout/schema.js';

import Transform from '../src/transform/processor.js';
import TransformSchema from '../src/transform/schema.js';

import Window from '../src/window/processor.js';
import WindowSchema from '../src/window/schema.js';

export const ASSETS = {
    accumulate: {
        Processor: Accumulate,
        Schema: AccumulateSchema,
    },
    accumulate_by_key: {
        Processor: AccumulateByKey,
        Schema: AccumulateByKeySchema,
    },
    add_key: {
        Processor: AddKey,
        Schema: AddKeySchema,
    },
    add_short_id: {
        Processor: AddShortId,
        Schema: AddShortIdSchema,
    },
    copy_field: {
        Processor: CopyField,
        Schema: CopyFieldSchema,
    },
    copy_metadata_field: {
        Processor: CopyMetadataField,
        Schema: CopyMetadataFieldSchema,
    },
    count_by_field: {
        Processor: CountByField,
        Schema: CountByFieldSchema,
    },
    count_unique: {
        Processor: CountUnique,
        Schema: CountUniqueSchema,
    },
    create_geopoint: {
        Processor: CreateGeopoint,
        Schema: CreateGeopointSchema,
    },
    data_generator: {
        Fetcher: DataGeneratorFetcher,
        Schema: DataGeneratorSchema,
        Slicer: DataGeneratorSlicer,
    },
    data_window_to_array: {
        Processor: DataWindowToArray,
        Schema: DataWindowToArraySchema,
    },
    date_router: {
        Processor: DateRouter,
        Schema: DateRouterSchema,
    },
    debug_routes: {
        Processor: DebugRoutes,
        Schema: DebugRoutesSchema,
    },
    dedupe: {
        Processor: Dedupe,
        Schema: DedupeSchema,
    },
    drop_field: {
        Processor: DropField,
        Schema: DropFieldSchema,
    },
    drop_field_conditional: {
        Processor: DropFieldConditional,
        Schema: DropFieldConditionalSchema,
    },
    extraction: {
        Processor: Extraction,
        Schema: ExtractionSchema,
    },
    field_router: {
        Processor: FieldRouter,
        Schema: FieldRouterSchema,
    },
    filter: {
        Processor: Filter,
        Schema: FilterSchema,
    },
    filter_by_date: {
        Processor: FilterByDate,
        Schema: FilterByDateSchema,
    },
    filter_by_required_fields: {
        Processor: FilterByRequiredFields,
        Schema: FilterByRequiredFieldsSchema,
    },
    filter_by_unknown_fields: {
        Processor: FilterByUnknownFields,
        Schema: FilterByUnknownFieldsSchema,
    },
    flatten_object: {
        Processor: FlattenObject,
        Schema: FlattenObjectSchema,
    },
    group_by: {
        Processor: GroupBy,
        Schema: GroupBySchema,
    },
    hash_router: {
        Processor: HashRouter,
        Schema: HashRouterSchema,
    },
    json_parser: {
        Processor: JsonParser,
        Schema: JsonParserSchema,
    },
    keep_field: {
        Processor: KeepField,
        Schema: KeepFieldSchema,
    },
    key_router: {
        Processor: KeyRouter,
        Schema: KeyRouterSchema,
    },
    match: {
        Processor: Match,
        Schema: MatchSchema,
    },
    output: {
        Processor: Output,
        Schema: OutputSchema,
    },
    post_process: {
        Processor: PostProcess,
        Schema: PostProcessSchema,
    },
    remove_empty_fields: {
        Processor: RemoveEmptyFields,
        Schema: RemoveEmptyFieldsSchema,
    },
    remove_key: {
        Processor: RemoveKey,
        Schema: RemoveKeySchema,
    },
    rename_field: {
        Processor: RenameField,
        Schema: RenameFieldSchema,
    },
    routed_sender: {
        Processor: RoutedSender,
        Schema: RoutedSenderSchema,
    },
    sample_exact: {
        Processor: SampleExact,
        Schema: SampleExactSchema,
    },
    sample_exact_es_percent: {
        Processor: SampleExactEsPercent,
        Schema: SampleExactEsPercentSchema,
    },
    sample_random: {
        Processor: SampleRandom,
        Schema: SampleRandomSchema,
    },
    selection: {
        Processor: Selection,
        Schema: SelectionSchema,
    },
    set_field: {
        Processor: SetField,
        Schema: SetFieldSchema,
    },
    set_field_conditional: {
        Processor: SetFieldConditional,
        Schema: SetFieldConditionalSchema,
    },
    set_key: {
        Processor: SetKey,
        Schema: SetKeySchema,
    },
    sort: {
        Processor: Sort,
        Schema: SortSchema,
    },
    stdout: {
        Processor: Stdout,
        Schema: StdoutSchema,
    },
    transform: {
        Processor: Transform,
        Schema: TransformSchema,
    },
    window: {
        Processor: Window,
        Schema: WindowSchema,
    },
};
