name: Daily Docker Cache

on:
  schedule:
    - cron: '0 8 * * 1-5' # Monday - Friday at 1 am Arizona Time
  workflow_dispatch:

permissions: {}

jobs:
  call-refresh-docker-cache-workflow:
    uses: terascope/workflows/.github/workflows/refresh-docker-cache.yml@2e12a5feded0f4ff6fc3143a0abf088029bcc05f
    permissions:
      actions: write
      contents: read
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
